# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@1.1
jobs:
  node-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test

  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run build
            - run:
                name: Installing deployment dependencies
                command: |
                  sudo apt-get -y -qq update
                  sudo apt-get install python3-pip python3-dev build-essential
                  sudo pip install --upgrade setuptools
                  sudo pip install awsebcli --upgrade
            - run:
                name: Deploying
                command: eb deploy Blueocean-env
workflows:
  test-only:
    jobs:
      - node-test
  build-test-deploy:
    jobs:
      - node-test
      - build-and-deploy:
          requires:
            - node-test
          context: aws
          filters:
            branches:
              only:
                - main
